/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type LocalizedImage = {
  _type: "localizedImage";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: LocalizedString;
};

export type LocalizedBlockContent = {
  _type: "localizedBlockContent";
  mk?: BlockContent;
  en?: BlockContent;
  sr?: BlockContent;
};

export type LocalizedText = {
  _type: "localizedText";
  mk?: string;
  en?: string;
  sr?: string;
};

export type LocalizedString = {
  _type: "localizedString";
  mk?: string;
  en?: string;
  sr?: string;
};

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type Topic = {
  _id: string;
  _type: "topic";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: LocalizedString;
  slug?: Slug;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: LocalizedString;
  roles?: LocalizedString;
  tagline?: LocalizedString;
  heroIntro?: LocalizedText;
  photo?: LocalizedImage;
  shortBio?: LocalizedText;
  bio?: LocalizedBlockContent;
  socialLinks?: Array<{
    platform?: string;
    url?: string;
    _type: "socialLink";
    _key: string;
  }>;
  email?: string;
};

export type Book = {
  _id: string;
  _type: "book";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: LocalizedString;
  tagline?: LocalizedString;
  coverImage?: LocalizedImage;
  description?: LocalizedBlockContent;
  genre?: LocalizedString;
  publisher?: string;
  publicationYear?: number;
  isbn?: string;
  purchaseLinks?: Array<{
    label?: LocalizedString;
    url?: string;
    _type: "purchaseLink";
    _key: string;
  }>;
};

export type TopicReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "topic";
};

export type Review = {
  _id: string;
  _type: "review";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  reviewTitle?: LocalizedString;
  slug?: Slug;
  coverImage?: LocalizedImage;
  bookTitle?: LocalizedString;
  bookAuthor?: string;
  publisher?: string;
  publicationYear?: number;
  isbn?: string;
  excerpt?: LocalizedText;
  body?: LocalizedBlockContent;
  topics?: Array<
    {
      _key: string;
    } & TopicReference
  >;
  source?: {
    sourceName?: string;
    sourceUrl?: string;
  };
  publishedAt?: string;
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: LocalizedString;
  slug?: Slug;
  excerpt?: LocalizedText;
  coverImage?: LocalizedImage;
  body?: LocalizedBlockContent;
  topics?: Array<
    {
      _key: string;
    } & TopicReference
  >;
  publishedAt?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | LocalizedImage
  | LocalizedBlockContent
  | LocalizedText
  | LocalizedString
  | BlockContent
  | Topic
  | Slug
  | Author
  | Book
  | TopicReference
  | Review
  | Post
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/lib/queries.ts
// Variable: REVIEWS_QUERY
// Query: *[_type == "review" && defined(slug.current)] | order(coalesce(publishedAt, _createdAt) desc) {    _id,    "slug": slug.current,    reviewTitle,    excerpt,    coverImage,    bookAuthor,    publishedAt  }
export type REVIEWS_QUERY_RESULT = Array<{
  _id: string;
  slug: string | null;
  reviewTitle: LocalizedString | null;
  excerpt: LocalizedText | null;
  coverImage: LocalizedImage | null;
  bookAuthor: string | null;
  publishedAt: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: POSTS_QUERY
// Query: *[_type == "post" && defined(slug.current)] | order(coalesce(publishedAt, _createdAt) desc) {    _id,    "slug": slug.current,    title,    excerpt,    publishedAt  }
export type POSTS_QUERY_RESULT = Array<{
  _id: string;
  slug: string | null;
  title: LocalizedString | null;
  excerpt: LocalizedText | null;
  publishedAt: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: BOOK_QUERY
// Query: *[_type == "book"][0]{    _id,    title,    tagline,    genre,    coverImage,    publisher,    publicationYear  }
export type BOOK_QUERY_RESULT = {
  _id: string;
  title: LocalizedString | null;
  tagline: LocalizedString | null;
  genre: LocalizedString | null;
  coverImage: LocalizedImage | null;
  publisher: string | null;
  publicationYear: number | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: AUTHOR_QUERY
// Query: *[_type == "author"][0]{    _id,    name,    roles,    shortBio,    photo  }
export type AUTHOR_QUERY_RESULT = {
  _id: string;
  name: LocalizedString | null;
  roles: LocalizedString | null;
  shortBio: LocalizedText | null;
  photo: LocalizedImage | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: HOME_REVIEWS_QUERY
// Query: *[_type == "review" && defined(slug.current)]    | order(coalesce(publishedAt, _createdAt) desc)[0...3]{    _id,    "slug": slug.current,    reviewTitle,    bookTitle,    bookAuthor,    excerpt,    coverImage,    publishedAt,    "topics": topics[]->{ _id, title }  }
export type HOME_REVIEWS_QUERY_RESULT = Array<{
  _id: string;
  slug: string | null;
  reviewTitle: LocalizedString | null;
  bookTitle: LocalizedString | null;
  bookAuthor: string | null;
  excerpt: LocalizedText | null;
  coverImage: LocalizedImage | null;
  publishedAt: string | null;
  topics: Array<{
    _id: string;
    title: LocalizedString | null;
  }> | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: HOME_POSTS_QUERY
// Query: *[_type == "post" && defined(slug.current)]    | order(coalesce(publishedAt, _createdAt) desc)[0...3]{    _id,    "slug": slug.current,    title,    excerpt,    publishedAt  }
export type HOME_POSTS_QUERY_RESULT = Array<{
  _id: string;
  slug: string | null;
  title: LocalizedString | null;
  excerpt: LocalizedText | null;
  publishedAt: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: HOME_FEATURED_BOOK_QUERY
// Query: *[_type == "book"][0]{    _id,    title,    tagline,    coverImage,    publisher,    publicationYear  }
export type HOME_FEATURED_BOOK_QUERY_RESULT = {
  _id: string;
  title: LocalizedString | null;
  tagline: LocalizedString | null;
  coverImage: LocalizedImage | null;
  publisher: string | null;
  publicationYear: number | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: HOME_HERO_QUERY
// Query: *[_type == "author"][0]{    _id,    name,    tagline,    heroIntro,    photo  }
export type HOME_HERO_QUERY_RESULT = {
  _id: string;
  name: LocalizedString | null;
  tagline: LocalizedString | null;
  heroIntro: LocalizedText | null;
  photo: LocalizedImage | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "review" && defined(slug.current)] | order(coalesce(publishedAt, _createdAt) desc) {\n    _id,\n    "slug": slug.current,\n    reviewTitle,\n    excerpt,\n    coverImage,\n    bookAuthor,\n    publishedAt\n  }\n': REVIEWS_QUERY_RESULT;
    '\n  *[_type == "post" && defined(slug.current)] | order(coalesce(publishedAt, _createdAt) desc) {\n    _id,\n    "slug": slug.current,\n    title,\n    excerpt,\n    publishedAt\n  }\n': POSTS_QUERY_RESULT;
    '\n  *[_type == "book"][0]{\n    _id,\n    title,\n    tagline,\n    genre,\n    coverImage,\n    publisher,\n    publicationYear\n  }\n': BOOK_QUERY_RESULT;
    '\n  *[_type == "author"][0]{\n    _id,\n    name,\n    roles,\n    shortBio,\n    photo\n  }\n': AUTHOR_QUERY_RESULT;
    '\n  *[_type == "review" && defined(slug.current)]\n    | order(coalesce(publishedAt, _createdAt) desc)[0...3]{\n    _id,\n    "slug": slug.current,\n    reviewTitle,\n    bookTitle,\n    bookAuthor,\n    excerpt,\n    coverImage,\n    publishedAt,\n    "topics": topics[]->{ _id, title }\n  }\n': HOME_REVIEWS_QUERY_RESULT;
    '\n  *[_type == "post" && defined(slug.current)]\n    | order(coalesce(publishedAt, _createdAt) desc)[0...3]{\n    _id,\n    "slug": slug.current,\n    title,\n    excerpt,\n    publishedAt\n  }\n': HOME_POSTS_QUERY_RESULT;
    '\n  *[_type == "book"][0]{\n    _id,\n    title,\n    tagline,\n    coverImage,\n    publisher,\n    publicationYear\n  }\n': HOME_FEATURED_BOOK_QUERY_RESULT;
    '\n  *[_type == "author"][0]{\n    _id,\n    name,\n    tagline,\n    heroIntro,\n    photo\n  }\n': HOME_HERO_QUERY_RESULT;
  }
}
