/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type LocalizedImage = {
  _type: "localizedImage";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: LocalizedString;
};

export type LocalizedBlockContent = {
  _type: "localizedBlockContent";
  mk?: BlockContent;
  en?: BlockContent;
  sr?: BlockContent;
};

export type LocalizedText = {
  _type: "localizedText";
  mk?: string;
  en?: string;
  sr?: string;
};

export type LocalizedString = {
  _type: "localizedString";
  mk?: string;
  en?: string;
  sr?: string;
};

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type Topic = {
  _id: string;
  _type: "topic";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: LocalizedString;
  slug?: Slug;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: LocalizedString;
  roles?: LocalizedString;
  tagline?: LocalizedString;
  heroIntro?: LocalizedText;
  photo?: LocalizedImage;
  shortBio?: LocalizedText;
  bio?: LocalizedBlockContent;
  education?: LocalizedString;
  translations?: Array<{
    title?: string;
    originalAuthor?: string;
    fromLang?: "mk" | "sr" | "bg" | "hr" | "en" | "fr";
    toLang?: "mk" | "sr" | "bg" | "hr" | "en" | "fr";
    publisher?: string;
    year?: number;
    kind?: "book" | "play" | "anthology";
    _type: "translation";
    _key: string;
  }>;
  socialLinks?: Array<{
    platform?: string;
    url?: string;
    _type: "socialLink";
    _key: string;
  }>;
  email?: string;
};

export type Book = {
  _id: string;
  _type: "book";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: LocalizedString;
  tagline?: LocalizedString;
  coverImage?: LocalizedImage;
  description?: LocalizedBlockContent;
  genre?: LocalizedString;
  publisher?: string;
  publicationYear?: number;
  isbn?: string;
  purchaseLinks?: Array<{
    label?: LocalizedString;
    url?: string;
    _type: "purchaseLink";
    _key: string;
  }>;
};

export type TopicReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "topic";
};

export type Review = {
  _id: string;
  _type: "review";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  reviewTitle?: LocalizedString;
  slug?: Slug;
  coverImage?: LocalizedImage;
  bookTitle?: LocalizedString;
  bookAuthor?: string;
  publisher?: string;
  publicationYear?: number;
  isbn?: string;
  excerpt?: LocalizedText;
  body?: LocalizedBlockContent;
  topics?: Array<
    {
      _key: string;
    } & TopicReference
  >;
  source?: {
    sourceName?: string;
    sourceUrl?: string;
  };
  publishedAt?: string;
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: LocalizedString;
  slug?: Slug;
  excerpt?: LocalizedText;
  coverImage?: LocalizedImage;
  body?: LocalizedBlockContent;
  topics?: Array<
    {
      _key: string;
    } & TopicReference
  >;
  source?: {
    sourceName?: string;
    sourceUrl?: string;
  };
  publishedAt?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | LocalizedImage
  | LocalizedBlockContent
  | LocalizedText
  | LocalizedString
  | BlockContent
  | Topic
  | Slug
  | Author
  | Book
  | TopicReference
  | Review
  | Post
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/lib/queries.ts
// Variable: REVIEWS_LIST_QUERY
// Query: *[_type == "review" && defined(slug.current)] | order(coalesce(publishedAt, _createdAt) desc) {    _id,    "slug": slug.current,    reviewTitle,    bookTitle,    bookAuthor,    excerpt,    coverImage,    publishedAt,    "topics": topics[]->{ _id, "slug": slug.current, title }  }
export type REVIEWS_LIST_QUERY_RESULT = Array<{
  _id: string;
  slug: string | null;
  reviewTitle: LocalizedString | null;
  bookTitle: LocalizedString | null;
  bookAuthor: string | null;
  excerpt: LocalizedText | null;
  coverImage: LocalizedImage | null;
  publishedAt: string | null;
  topics: Array<{
    _id: string;
    slug: string | null;
    title: LocalizedString | null;
  }> | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: REVIEWS_SEARCH_QUERY
// Query: *[_type == "review" && defined(slug.current)] | order(coalesce(publishedAt, _createdAt) desc) {    _id,    "slug": slug.current,    reviewTitle,    bookTitle,    bookAuthor,    excerpt,    coverImage,    publishedAt,    body,    "topics": topics[]->{ _id, "slug": slug.current, title }  }
export type REVIEWS_SEARCH_QUERY_RESULT = Array<{
  _id: string;
  slug: string | null;
  reviewTitle: LocalizedString | null;
  bookTitle: LocalizedString | null;
  bookAuthor: string | null;
  excerpt: LocalizedText | null;
  coverImage: LocalizedImage | null;
  publishedAt: string | null;
  body: LocalizedBlockContent | null;
  topics: Array<{
    _id: string;
    slug: string | null;
    title: LocalizedString | null;
  }> | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: REVIEW_BY_SLUG_QUERY
// Query: *[_type == "review" && slug.current == $slug][0]{    _id,    _updatedAt,    "slug": slug.current,    reviewTitle,    bookTitle,    bookAuthor,    publisher,    publicationYear,    excerpt,    body,    coverImage,    publishedAt,    source,    "topics": topics[]->{ _id, "slug": slug.current, title }  }
export type REVIEW_BY_SLUG_QUERY_RESULT = {
  _id: string;
  _updatedAt: string;
  slug: string | null;
  reviewTitle: LocalizedString | null;
  bookTitle: LocalizedString | null;
  bookAuthor: string | null;
  publisher: string | null;
  publicationYear: number | null;
  excerpt: LocalizedText | null;
  body: LocalizedBlockContent | null;
  coverImage: LocalizedImage | null;
  publishedAt: string | null;
  source: {
    sourceName?: string;
    sourceUrl?: string;
  } | null;
  topics: Array<{
    _id: string;
    slug: string | null;
    title: LocalizedString | null;
  }> | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: REVIEW_SLUGS_QUERY
// Query: *[_type == "review" && defined(slug.current)]{ "slug": slug.current }
export type REVIEW_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: TOPICS_QUERY
// Query: *[_type == "topic" && defined(slug.current)] | order(title.mk asc){    _id,    "slug": slug.current,    title  }
export type TOPICS_QUERY_RESULT = Array<{
  _id: string;
  slug: string | null;
  title: LocalizedString | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: POSTS_LIST_QUERY
// Query: *[_type == "post" && defined(slug.current)] | order(coalesce(publishedAt, _createdAt) desc) {    _id,    "slug": slug.current,    title,    excerpt,    coverImage,    publishedAt,    "topics": topics[]->{ _id, "slug": slug.current, title }  }
export type POSTS_LIST_QUERY_RESULT = Array<{
  _id: string;
  slug: string | null;
  title: LocalizedString | null;
  excerpt: LocalizedText | null;
  coverImage: LocalizedImage | null;
  publishedAt: string | null;
  topics: Array<{
    _id: string;
    slug: string | null;
    title: LocalizedString | null;
  }> | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: POST_BY_SLUG_QUERY
// Query: *[_type == "post" && slug.current == $slug][0]{    _id,    _updatedAt,    "slug": slug.current,    title,    excerpt,    body,    coverImage,    publishedAt,    source,    "topics": topics[]->{ _id, "slug": slug.current, title }  }
export type POST_BY_SLUG_QUERY_RESULT = {
  _id: string;
  _updatedAt: string;
  slug: string | null;
  title: LocalizedString | null;
  excerpt: LocalizedText | null;
  body: LocalizedBlockContent | null;
  coverImage: LocalizedImage | null;
  publishedAt: string | null;
  source: {
    sourceName?: string;
    sourceUrl?: string;
  } | null;
  topics: Array<{
    _id: string;
    slug: string | null;
    title: LocalizedString | null;
  }> | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: POST_SLUGS_QUERY
// Query: *[_type == "post" && defined(slug.current)]{ "slug": slug.current }
export type POST_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: BOOK_QUERY
// Query: *[_type == "book"][0]{    _id,    title,    coverImage,    description,    purchaseLinks,    publisher,    publicationYear,    "authorName": *[_type == "author"][0].name  }
export type BOOK_QUERY_RESULT = {
  _id: string;
  title: LocalizedString | null;
  coverImage: LocalizedImage | null;
  description: LocalizedBlockContent | null;
  purchaseLinks: Array<{
    label?: LocalizedString;
    url?: string;
    _type: "purchaseLink";
    _key: string;
  }> | null;
  publisher: string | null;
  publicationYear: number | null;
  authorName: LocalizedString | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: ABOUT_QUERY
// Query: *[_type == "author"][0]{    _id,    name,    roles,    tagline,    bio,    photo,    education,    translations[]{      title,      originalAuthor,      fromLang,      toLang,      publisher,      year,      kind    }  }
export type ABOUT_QUERY_RESULT = {
  _id: string;
  name: LocalizedString | null;
  roles: LocalizedString | null;
  tagline: LocalizedString | null;
  bio: LocalizedBlockContent | null;
  photo: LocalizedImage | null;
  education: LocalizedString | null;
  translations: Array<{
    title: string | null;
    originalAuthor: string | null;
    fromLang: "bg" | "en" | "fr" | "hr" | "mk" | "sr" | null;
    toLang: "bg" | "en" | "fr" | "hr" | "mk" | "sr" | null;
    publisher: string | null;
    year: number | null;
    kind: "anthology" | "book" | "play" | null;
  }> | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: HOME_REVIEWS_QUERY
// Query: *[_type == "review" && defined(slug.current)]    | order(coalesce(publishedAt, _createdAt) desc)[0...3]{    _id,    "slug": slug.current,    reviewTitle,    bookTitle,    bookAuthor,    excerpt,    coverImage,    publishedAt,    "topics": topics[]->{ _id, title }  }
export type HOME_REVIEWS_QUERY_RESULT = Array<{
  _id: string;
  slug: string | null;
  reviewTitle: LocalizedString | null;
  bookTitle: LocalizedString | null;
  bookAuthor: string | null;
  excerpt: LocalizedText | null;
  coverImage: LocalizedImage | null;
  publishedAt: string | null;
  topics: Array<{
    _id: string;
    title: LocalizedString | null;
  }> | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: HOME_POSTS_QUERY
// Query: *[_type == "post" && defined(slug.current)]    | order(coalesce(publishedAt, _createdAt) desc)[0...3]{    _id,    "slug": slug.current,    title,    excerpt,    publishedAt  }
export type HOME_POSTS_QUERY_RESULT = Array<{
  _id: string;
  slug: string | null;
  title: LocalizedString | null;
  excerpt: LocalizedText | null;
  publishedAt: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: HOME_FEATURED_BOOK_QUERY
// Query: *[_type == "book"][0]{    _id,    title,    tagline,    coverImage,    publisher,    publicationYear  }
export type HOME_FEATURED_BOOK_QUERY_RESULT = {
  _id: string;
  title: LocalizedString | null;
  tagline: LocalizedString | null;
  coverImage: LocalizedImage | null;
  publisher: string | null;
  publicationYear: number | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: HOME_HERO_QUERY
// Query: *[_type == "author"][0]{    _id,    name,    tagline,    heroIntro,    photo  }
export type HOME_HERO_QUERY_RESULT = {
  _id: string;
  name: LocalizedString | null;
  tagline: LocalizedString | null;
  heroIntro: LocalizedText | null;
  photo: LocalizedImage | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "review" && defined(slug.current)] | order(coalesce(publishedAt, _createdAt) desc) {\n    _id,\n    "slug": slug.current,\n    reviewTitle,\n    bookTitle,\n    bookAuthor,\n    excerpt,\n    coverImage,\n    publishedAt,\n    "topics": topics[]->{ _id, "slug": slug.current, title }\n  }\n': REVIEWS_LIST_QUERY_RESULT;
    '\n  *[_type == "review" && defined(slug.current)] | order(coalesce(publishedAt, _createdAt) desc) {\n    _id,\n    "slug": slug.current,\n    reviewTitle,\n    bookTitle,\n    bookAuthor,\n    excerpt,\n    coverImage,\n    publishedAt,\n    body,\n    "topics": topics[]->{ _id, "slug": slug.current, title }\n  }\n': REVIEWS_SEARCH_QUERY_RESULT;
    '\n  *[_type == "review" && slug.current == $slug][0]{\n    _id,\n    _updatedAt,\n    "slug": slug.current,\n    reviewTitle,\n    bookTitle,\n    bookAuthor,\n    publisher,\n    publicationYear,\n    excerpt,\n    body,\n    coverImage,\n    publishedAt,\n    source,\n    "topics": topics[]->{ _id, "slug": slug.current, title }\n  }\n': REVIEW_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "review" && defined(slug.current)]{ "slug": slug.current }\n': REVIEW_SLUGS_QUERY_RESULT;
    '\n  *[_type == "topic" && defined(slug.current)] | order(title.mk asc){\n    _id,\n    "slug": slug.current,\n    title\n  }\n': TOPICS_QUERY_RESULT;
    '\n  *[_type == "post" && defined(slug.current)] | order(coalesce(publishedAt, _createdAt) desc) {\n    _id,\n    "slug": slug.current,\n    title,\n    excerpt,\n    coverImage,\n    publishedAt,\n    "topics": topics[]->{ _id, "slug": slug.current, title }\n  }\n': POSTS_LIST_QUERY_RESULT;
    '\n  *[_type == "post" && slug.current == $slug][0]{\n    _id,\n    _updatedAt,\n    "slug": slug.current,\n    title,\n    excerpt,\n    body,\n    coverImage,\n    publishedAt,\n    source,\n    "topics": topics[]->{ _id, "slug": slug.current, title }\n  }\n': POST_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "post" && defined(slug.current)]{ "slug": slug.current }\n': POST_SLUGS_QUERY_RESULT;
    '\n  *[_type == "book"][0]{\n    _id,\n    title,\n    coverImage,\n    description,\n    purchaseLinks,\n    publisher,\n    publicationYear,\n    "authorName": *[_type == "author"][0].name\n  }\n': BOOK_QUERY_RESULT;
    '\n  *[_type == "author"][0]{\n    _id,\n    name,\n    roles,\n    tagline,\n    bio,\n    photo,\n    education,\n    translations[]{\n      title,\n      originalAuthor,\n      fromLang,\n      toLang,\n      publisher,\n      year,\n      kind\n    }\n  }\n': ABOUT_QUERY_RESULT;
    '\n  *[_type == "review" && defined(slug.current)]\n    | order(coalesce(publishedAt, _createdAt) desc)[0...3]{\n    _id,\n    "slug": slug.current,\n    reviewTitle,\n    bookTitle,\n    bookAuthor,\n    excerpt,\n    coverImage,\n    publishedAt,\n    "topics": topics[]->{ _id, title }\n  }\n': HOME_REVIEWS_QUERY_RESULT;
    '\n  *[_type == "post" && defined(slug.current)]\n    | order(coalesce(publishedAt, _createdAt) desc)[0...3]{\n    _id,\n    "slug": slug.current,\n    title,\n    excerpt,\n    publishedAt\n  }\n': HOME_POSTS_QUERY_RESULT;
    '\n  *[_type == "book"][0]{\n    _id,\n    title,\n    tagline,\n    coverImage,\n    publisher,\n    publicationYear\n  }\n': HOME_FEATURED_BOOK_QUERY_RESULT;
    '\n  *[_type == "author"][0]{\n    _id,\n    name,\n    tagline,\n    heroIntro,\n    photo\n  }\n': HOME_HERO_QUERY_RESULT;
  }
}
