/**
 * scripts/import-assets.mts — Phase 2.01e image import.
 *
 * Uploads Dalibor's real images (gathered by Cowork in Phase 2.01d) into the
 * `production` dataset and sets the matching `localizedImage` fields, WITHOUT
 * clobbering any image a Studio editor may have already set.
 *
 *   • Input  — `content-packet/assets/assets.json` (+ the image files beside it).
 *   • Output — each `use:true` entry's asset uploaded + its target field patched
 *              to { _type:"localizedImage", asset:{_ref}, alt:{mk,en,sr} }.
 *
 * Mirrors `scripts/import-content.mts`: same WRITE client (token from
 * `SANITY_WRITE_TOKEN` in `.env.local`, `useCdn:false`), same `--dry-run`, the
 * same abort-before-write "Zaporožac" scrub, and an idempotent, skip-if-set
 * approach so a re-run is a genuine no-op.
 *
 * Safety / idempotency:
 *   • PRESERVE-IF-SET — if the target field already carries an `asset._ref`, the
 *     entry is SKIPPED (never overwritten), so a Studio-side upload is never lost.
 *     Pass `--force` to re-upload + overwrite anyway.
 *   • Sanity asset ids are content-hash-based, so re-uploading identical bytes
 *     returns the SAME asset id — uploads are naturally idempotent.
 *   • `favicon_source` is IGNORED here (target:null) — the browser-tab icon is
 *     generated by `scripts/make-favicon.mts`, not written to a CMS field.
 *   • Fails loudly (non-zero exit) on a missing file, a missing `alt.mk` for a
 *     `use:true` entry, an unknown/absent target document, or an unknown image
 *     extension.
 *
 * Run:  npm run import:assets              (add --dry-run to plan only)
 *       npm run import:assets -- --force   (re-upload + overwrite already-set fields)
 *   ( = node --conditions=react-server --import tsx --env-file=.env.local
 *         scripts/import-assets.mts )
 */
import {existsSync, readFileSync} from "node:fs";
import path from "node:path";

import {createClient} from "next-sanity";

import {apiVersion, dataset, projectId} from "@/sanity/env";

const DRY_RUN = process.argv.includes("--dry-run");
const FORCE = process.argv.includes("--force");
const ROOT = process.cwd();
const ASSETS_DIR = path.join(ROOT, "content-packet/assets");
const ASSETS_PATH = path.join(ASSETS_DIR, "assets.json");

/* ----------------------------------------------------------------------------
 * 0 · Preconditions
 * ------------------------------------------------------------------------- */
const token = process.env.SANITY_WRITE_TOKEN;
if (!token) {
  console.error(
    "Sanity write token not set in `.env.local` — Lazar must paste it before the " +
      "import can run. (Expected variable: SANITY_WRITE_TOKEN.)",
  );
  process.exit(1);
}
if (!existsSync(ASSETS_PATH)) {
  console.error(
    `Assets manifest missing: ${ASSETS_PATH}\n` +
      "Cowork's Phase 2.01d output (content-packet/assets/) must be present in this checkout.",
  );
  process.exit(1);
}

const writeClient = createClient({
  projectId,
  dataset,
  apiVersion,
  token,
  useCdn: false, // mutations + fresh reads
});

/* ----------------------------------------------------------------------------
 * 1 · Parse the manifest into a flat list of processable entries
 * ------------------------------------------------------------------------- */
type Target = {docId?: string; field?: string};
type AltSlots = {mk?: string; en?: string; sr?: string};
type AssetEntry = {
  file?: string | null;
  target?: Target | null;
  alt?: AltSlots;
  use?: boolean | string;
  note?: string;
};

// Named single-entry keys (each an object). `favicon_source` is deliberately
// NOT here — it carries target:null and is the browser-tab icon source, handled
// by scripts/make-favicon.mts.
const SINGLE_KEYS = ["author_photo", "book_cover"] as const;
// Array keys (each an array of entries; empty today).
const ARRAY_KEYS = ["reviewed_books", "blog_images", "banner"] as const;
const IGNORED_KEYS = new Set(["favicon_source"]);

const manifest = JSON.parse(readFileSync(ASSETS_PATH, "utf8")) as Record<
  string,
  unknown
>;

// Guard: surface any top-level key we don't handle, so a future category Cowork
// adds is never silently skipped (leaving an image un-imported / a placeholder).
for (const key of Object.keys(manifest)) {
  if (
    !SINGLE_KEYS.includes(key as (typeof SINGLE_KEYS)[number]) &&
    !ARRAY_KEYS.includes(key as (typeof ARRAY_KEYS)[number]) &&
    !IGNORED_KEYS.has(key)
  ) {
    console.warn(
      `WARNING: manifest has an unhandled top-level key "${key}" — it is being IGNORED. ` +
        "If it holds real images, extend SINGLE_KEYS/ARRAY_KEYS in scripts/import-assets.mts.",
    );
  }
}

type Labelled = {label: string; entry: AssetEntry};
const entries: Labelled[] = [];
for (const key of SINGLE_KEYS) {
  const value = manifest[key] as AssetEntry | undefined;
  if (value && typeof value === "object") entries.push({label: key, entry: value});
}
for (const key of ARRAY_KEYS) {
  const arr = manifest[key];
  if (Array.isArray(arr)) {
    arr.forEach((entry, i) =>
      entries.push({label: `${key}[${i}]`, entry: entry as AssetEntry}),
    );
  }
}

/* ----------------------------------------------------------------------------
 * 2 · "Zaporožac" scrub — abort before ANY write if a variant appears anywhere
 *     in the manifest (filenames, alt text, notes, sources — the whole input).
 * ------------------------------------------------------------------------- */
const SCRUB = /zaporo|запорож/i;
function scrub(value: unknown, said: string[] = [], trail = "$"): string[] {
  if (typeof value === "string") {
    if (SCRUB.test(value)) said.push(`${trail}: ${value.slice(0, 80)}`);
  } else if (Array.isArray(value)) {
    value.forEach((v, i) => scrub(v, said, `${trail}[${i}]`));
  } else if (value && typeof value === "object") {
    for (const [k, v] of Object.entries(value)) scrub(v, said, `${trail}.${k}`);
  }
  return said;
}
const hits = scrub(manifest);
if (hits.length > 0) {
  console.error("ABORT: 'Zaporožac' variant found in the assets manifest:");
  hits.forEach((h) => console.error(`  - ${h}`));
  process.exit(1);
}
console.log("Zaporožac scrub: 0 hits across the assets manifest. ✓");

/* ----------------------------------------------------------------------------
 * 3 · Helpers
 * ------------------------------------------------------------------------- */
const CONTENT_TYPES: Record<string, string> = {
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".png": "image/png",
  ".webp": "image/webp",
  ".gif": "image/gif",
  ".avif": "image/avif",
};
function contentTypeFor(file: string): string {
  const ext = path.extname(file).toLowerCase();
  const type = CONTENT_TYPES[ext];
  if (!type) {
    console.error(
      `ABORT: unknown image extension "${ext}" for "${file}" — add it to CONTENT_TYPES.`,
    );
    process.exit(1);
  }
  return type;
}

/** Drop empty/undefined slots so we never write an empty alt string. */
function cleanAlt(alt: AltSlots): AltSlots {
  return Object.fromEntries(
    Object.entries(alt).filter(([, v]) => typeof v === "string" && v.trim() !== ""),
  ) as AltSlots;
}

/* ----------------------------------------------------------------------------
 * 4 · Process each entry — preserve-if-set, upload, patch.
 * ------------------------------------------------------------------------- */
const results: {
  uploaded: number;
  set: number;
  skipped: number; // already-set → preserved
  held: number; // use !== true
  perTarget: string[];
} = {uploaded: 0, set: 0, skipped: 0, held: 0, perTarget: []};

console.log(
  DRY_RUN
    ? "\n[--dry-run] Planning asset import (nothing will be written):"
    : `\nImporting assets into \`production\`${FORCE ? " (--force: overwriting set fields)" : ""}…`,
);

for (const {label, entry} of entries) {
  // Held — anything not explicitly use:true (e.g. use:"hold", use:false, unset).
  if (entry.use !== true) {
    results.held++;
    const where = entry.target?.docId
      ? `${entry.target.docId}.${entry.target.field ?? "?"}`
      : "(no target)";
    results.perTarget.push(`held     ${label} → ${where}  (use=${JSON.stringify(entry.use)})`);
    console.log(`  held     ${label}  (use=${JSON.stringify(entry.use)})`);
    continue;
  }

  // use:true — validate the entry fully before any network call.
  if (!entry.file) {
    console.error(`ABORT: ${label} is use:true but has no "file".`);
    process.exit(1);
  }
  if (!entry.target?.docId || !entry.target?.field) {
    console.error(`ABORT: ${label} is use:true but has no target { docId, field }.`);
    process.exit(1);
  }
  const abs = path.join(ASSETS_DIR, entry.file);
  if (!existsSync(abs)) {
    console.error(`ABORT: ${label} references a missing file: ${entry.file}`);
    process.exit(1);
  }
  const alt = cleanAlt(entry.alt ?? {});
  if (!alt.mk?.trim()) {
    console.error(
      `ABORT: ${label} (use:true) has no Macedonian alt (alt.mk) — the schema requires it once an image is set.`,
    );
    process.exit(1);
  }
  const contentType = contentTypeFor(entry.file);
  const {docId, field} = entry.target;

  // Unknown-docId guard + preserve-if-set: fetch the target doc.
  const doc = await writeClient.fetch<Record<string, unknown> | null>(
    `*[_id == $id][0]`,
    {id: docId},
  );
  if (!doc) {
    console.error(
      `ABORT: ${label} targets an unknown/absent document (_id "${docId}") — nothing to patch.`,
    );
    process.exit(1);
  }
  const currentField = doc[field] as {asset?: {_ref?: string}} | undefined;
  const existingRef = currentField?.asset?._ref;

  if (existingRef && !FORCE) {
    results.skipped++;
    results.perTarget.push(`skipped  ${label} → ${docId}.${field}  (already set — preserved)`);
    console.log(`  skipped  ${label} → ${docId}.${field}  (already set — preserved; --force to overwrite)`);
    continue;
  }

  if (DRY_RUN) {
    results.uploaded++;
    results.set++;
    const note = existingRef ? " (FORCE overwrite of an already-set field)" : "";
    results.perTarget.push(`would-set ${label} → ${docId}.${field}  [${entry.file}]${note}`);
    console.log(`  would-set ${label} → ${docId}.${field}  ← ${entry.file}${note}`);
    continue;
  }

  // Upload the asset (content-hash id → identical bytes reuse the same asset).
  const buffer = readFileSync(abs);
  const asset = await writeClient.assets.upload("image", buffer, {
    filename: path.basename(entry.file),
    contentType,
  });
  results.uploaded++;

  // Patch (NOT createOrReplace) so every other field on the doc is untouched.
  await writeClient
    .patch(docId)
    .set({
      [field]: {
        _type: "localizedImage",
        asset: {_type: "reference", _ref: asset._id},
        alt,
      },
    })
    .commit();
  results.set++;
  results.perTarget.push(`set      ${label} → ${docId}.${field}  (asset ${asset._id})`);
  console.log(`  set      ${label} → ${docId}.${field}  (asset ${asset._id})`);
}

/* ----------------------------------------------------------------------------
 * 5 · Tally
 * ------------------------------------------------------------------------- */
console.log(`\nDone${DRY_RUN ? " (dry run — nothing written)" : ""}.`);
console.log(
  `  tally → uploaded=${results.uploaded} set=${results.set} ` +
    `skipped(already-set)=${results.skipped} held(use!=true)=${results.held}`,
);
console.log("  per-target:");
for (const line of results.perTarget) console.log(`    ${line}`);
