import type { Metadata, Viewport } from "next";
import { notFound } from "next/navigation";
import { Lora, Playfair_Display } from "next/font/google";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { getTranslations, setRequestLocale } from "next-intl/server";
import { Analytics } from "@vercel/analytics/next";

import { SiteFooter } from "@/components/layout/site-footer";
import { SiteHeader } from "@/components/layout/site-header";
import { SkipToContent } from "@/components/layout/skip-to-content";
import { routing } from "@/i18n/routing";
import { previewNoindex, siteUrl } from "@/sanity/env";

import "../globals.css";

// Display family — Playfair Display, latin + cyrillic (Appendix C). Exposed as
// `--font-playfair`, which `--font-display` in globals.css points at.
//
// Phase 3.01 font trim: `weight` is deliberately omitted so `next/font` ships the
// **variable** font instead of the static 500/600/700 instances. The handover
// (§3.1) uses Playfair at 600, 700 and 500-italic — three static cuts per script
// per style, i.e. 12 (weight × style × subset) combinations and 68 registered
// @font-face rules. One variable file per (style, subset) covers every weight in
// the range for fewer bytes and far fewer preloads, and it leaves the whole axis
// available should the design ever want a 550. `display: "swap"` is unchanged.
const playfair = Playfair_Display({
  subsets: ["latin", "cyrillic"],
  variable: "--font-playfair",
  display: "swap",
});

// Italic is split into its own instance purely so it can carry `preload: false`.
// Measured before the split, the four italic files (Playfair + Lora × latin +
// cyrillic) were 123 KB of a 244 KB preload on EVERY page — for pull-quotes
// (§6.10) and in-prose `<em>`, which most pages never render. Unpreloaded they
// still load on demand the moment italic text appears.
//
// The cost of splitting is that a separate instance is a separate font-family,
// so italic contexts have to name it: globals.css maps `em / i / cite / .italic`
// (and their `.font-display` variants) onto these variables. Without that the
// browser would find no italic face in the roman family and synthesise an
// oblique, which is exactly the mismatched-glyph problem §3.4 warns about.
const playfairItalic = Playfair_Display({
  subsets: ["latin", "cyrillic"],
  style: ["italic"],
  variable: "--font-playfair-italic",
  display: "swap",
  preload: false,
});

// Body / UI family — Lora, latin + cyrillic, wired to `--font-lora` / `--font-body`.
// Variable for the same reason (§3.1 uses 400, 500, 600 and 400-italic).
const lora = Lora({
  subsets: ["latin", "cyrillic"],
  variable: "--font-lora",
  display: "swap",
});

const loraItalic = Lora({
  subsets: ["latin", "cyrillic"],
  style: ["italic"],
  variable: "--font-lora-italic",
  display: "swap",
  preload: false,
});

/**
 * Viewport + theme colour (Phase 3.01). Exported from the *locale* layout, so it
 * is emitted per locale as the brief asks — the value is the same locked cream
 * page ground in all three, because the brand does not change by language.
 *
 * `viewportFit: "cover"` is the switch that makes `env(safe-area-inset-*)`
 * report real values; without it the insets are always 0 and the safe-area work
 * in globals.css would be dead code. `initialScale: 1` with no `maximumScale`
 * keeps pinch-zoom available (WCAG 2.2 AA SC 1.4.4).
 */
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
  themeColor: "#F4EDE1",
};

/**
 * Site-wide metadata defaults (Phase 1.12), localized per request:
 *  - `metadataBase` (from NEXT_PUBLIC_SITE_URL) so every relative URL — notably
 *    the file-convention `opengraph-image` — resolves to an absolute URL;
 *  - a `title.template` ("%s — siteName") that wraps every child page's title,
 *    plus a default title for routes that set none (e.g. error boundaries);
 *  - default description + Open Graph/Twitter, overridden per page by
 *    `buildPageMetadata`.
 * Per-page canonical, hreflang, and og:type are set by each page's
 * `generateMetadata` via `@/lib/seo/metadata`.
 */
export async function generateMetadata({
  params,
}: {
  params: Promise<{ locale: string }>;
}): Promise<Metadata> {
  const { locale } = await params;
  const resolved = hasLocale(routing.locales, locale)
    ? locale
    : routing.defaultLocale;
  const t = await getTranslations({ locale: resolved, namespace: "metadata" });
  const siteName = t("siteName");

  return {
    metadataBase: new URL(siteUrl),
    // Emits <link rel="manifest">; the document itself is generated by
    // `src/app/manifest.ts` (Phase 3.01).
    manifest: "/manifest.webmanifest",
    title: {
      default: t("default.title"),
      template: `%s — ${siteName}`,
    },
    description: t("default.description"),
    // Preview safety-net (2.05): when PREVIEW_NOINDEX is on, emit a hard
    // site-wide noindex. Set on the root layout so every child page inherits it
    // (no page's `buildPageMetadata` sets `robots`, so none override this).
    ...(previewNoindex
      ? { robots: { index: false, follow: false } }
      : {}),
    openGraph: {
      type: "website",
      siteName,
      title: t("default.title"),
      description: t("default.description"),
    },
    twitter: { card: "summary_large_image" },
  };
}

// Prerender all three locale roots.
export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  // Opt this locale into static rendering.
  setRequestLocale(locale);

  const t = await getTranslations("common");

  return (
    <html
      lang={locale}
      className={`${playfair.variable} ${playfairItalic.variable} ${lora.variable} ${loraItalic.variable}`}
    >
      <body className="flex min-h-dvh flex-col">
        <NextIntlClientProvider>
          {/* First focusable element — jumps keyboard users straight to <main>. */}
          <SkipToContent>{t("skipToContent")}</SkipToContent>
          <SiteHeader />
          <main id="content" tabIndex={-1} className="flex-1 outline-none">
            {children}
          </main>
          <SiteFooter />
        </NextIntlClientProvider>
        <Analytics />
      </body>
    </html>
  );
}
